Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -22,6 +22,19 @@ jobs:
         with:
           fetch-depth: 0
       
+      - name: 🛠️ Get Changelog Entry
+        id: changelog_reader
+        uses: mindsers/changelog-reader-action@v2
+        with:
+          version: Unreleased
+          path: ./CHANGELOG.md
+      
+      - name: Ensure release has changes
+        if: steps.changelog_reader.outputs.changes == ''
+        run: |
+          echo "::error file=CHANGELOG.md::The unreleased section in the changelog is empty. Nothing to release."
+          exit 1
+          
       - name: ⚙️ Import GPG key
         id: import_gpg
         uses: crazy-max/ghaction-import-gpg@v3
@@ -34,14 +47,12 @@ jobs:
           git config user.name ${{ steps.import_gpg.outputs.name }}
           git config user.email ${{ steps.import_gpg.outputs.email }}
           git config --global user.signingkey ${{ steps.import_gpg.outputs.keyid }}
-          git config --global commit.gpgsign true
+          git config --global commit.gpgsign true          
       
       - name: ⚙️ Setup GIT versioning
         uses: dotnet/nbgv@v0.4.0
         with:
-          setAllVars: true
-            
-      # TODO: only update CHANGELOG.md if unreleased section is not empty
+          setAllVars: true                
       
       - name: 🛠️ Update changelog
         uses: thomaseizinger/keep-a-changelog-new-release@1.2.1
@@ -56,12 +67,17 @@ jobs:
       - name: 🛠️ Building library in release mode
         run: dotnet pack -c release -p:ContinuousIntegrationBuild=true -p:PublicRelease=true
       
-      - name: 🛠️ Get Changelog Entry
-        id: changelog_reader
-        uses: mindsers/changelog-reader-action@v2
-        with:
-          version: ${{ env.NBGV_SimpleVersion }}
-          path: ./CHANGELOG.md
+      - name: 🛠️ Commit CHANGELOG.md to stable branch
+        run: |
+          git add CHANGELOG.md
+          git commit -m "Updated CHANGELOG.md for ${{ env.NBGV_SimpleVersion }} release"
+          git push origin stable
+
+      - name: ⏩ Merge stable with main
+        run: | 
+          git checkout main
+          git merge stable
+          git push origin main    
 
       - name: 🛠️ Create GitHub release
         uses: thomaseizinger/create-release@1.0.0
@@ -73,15 +89,3 @@ jobs:
           body: ${{ steps.changelog_reader.outputs.changes }}
           draft: false
           prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
-
-      - name: 🛠️ Commit CHANGELOG.md to stable branch
-        run: |
-          git add CHANGELOG.md
-          git commit -m "Updated CHANGELOG.md for ${{ env.NBGV_SimpleVersion }} release"
-          git push origin stable
-
-      - name: ⏩ Merge stable with main
-        run: | 
-          git checkout main
-          git merge stable
-          git push origin main
